name: cv
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/BinghamtonRover/Computer-Vision
publish_to: none

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  burt_network:
    git:
      url: https://github.com/BinghamtonRover/Networking
      ref: cv
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
